### ISSUE TITLE
Gulp build is not working after commit ~ fc435b2

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-web#290]
This is a known error:
https://github.com/Kagami/gulp-ng-annotate#faq

>That's not a gulp-ng-annotate or ng-annotate error: you passed the invalid JavaScript code to the plugin. Check your source code near the specified place.

And this makes `cap staging deploy` fail

### Expected behaviour
Should build without errors

### Actual behaviour
Error:
>events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: scripts/vendor-7604658e.js: error: couldn't process source due to parse error
Unexpected token (104737:10)
    at transform (/home/viktor/fablab/smartcitizen-web/node_modules/gulp-ng-annotate/index.js:20:11)
    at Transform._transform (/home/viktor/fablab/smartcitizen-web/node_modules/gulp-ng-annotate/index.js:68:25)
    at Transform._read (/home/viktor/fablab/smartcitizen-web/node_modules/gulp-ng-annotate/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/viktor/fablab/smartcitizen-web/node_modules/gulp-ng-annotate/node_modules/readable-stream/lib/_stream_transform.js:172:12)

### How to reproduce
` git checkout master; npm i; gulp build`
` git checkout fc435b2; npm i; gulp build`

**Comment by viktorsmari** [comment]
This is related to ngAnnotate in `gulp/build.js` erroring

**Comment by dsmrs** [comment]
fixed no? @viktorsmari

**Comment by viktorsmari** [comment]
Yes!
